# Generated by Django 3.2.22 on 2023-12-08 15:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('photo', models.URLField()),
                ('description', models.TextField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('biodata', models.JSONField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('name', models.CharField(max_length=255)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='SiteAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=60)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('data', models.JSONField()),
                ('fans', models.ManyToManyField(related_name='favourites', to='xselect.SiteAccount')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siteaccounts', to='xselect.site')),
            ],
            options={
                'ordering': ('account',),
            },
        ),
        migrations.CreateModel(
            name='SiteAccountCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('frequency', models.CharField(choices=[('30D', '30 Days'), ('31D', '31 Days'), ('1M', 'Month'), ('3M', '3 months'), ('6M', '6 months'), ('12M', '12 months')], max_length=4)),
                ('expiry_date', models.DateTimeField(null=True)),
                ('site_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siteaccountcharges', to='xselect.siteaccount')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreatorSiteAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('photo', models.URLField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatorsites', to='xselect.creator')),
                ('site_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatoraccounts', to='xselect.siteaccount')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='CreatorPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('deleted', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatorphotos', to='xselect.creator')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(max_length=120)),
                ('deleted', models.DateTimeField(default=None)),
                ('site_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='xselect.siteaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'site_account')},
            },
        ),
        migrations.CreateModel(
            name='SiteAccountRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.DateTimeField(default=None)),
                ('site_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='xselect.siteaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'site_account')},
            },
        ),
        migrations.AddConstraint(
            model_name='siteaccount',
            constraint=models.UniqueConstraint(fields=('site', 'account'), name='site_account_unique'),
        ),
        migrations.AlterUniqueTogether(
            name='creatorsiteaccount',
            unique_together={('creator', 'site_account')},
        ),
    ]
